# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beidou.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 668)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_port = QtWidgets.QGridLayout()
        self.gridLayout_port.setObjectName("gridLayout_port")
        self.label_port = QtWidgets.QLabel(self.centralwidget)
        self.label_port.setObjectName("label_port")
        self.gridLayout_port.addWidget(self.label_port, 0, 2, 1, 1)
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_port.addWidget(self.pushButton_connect, 0, 4, 1, 1)
        self.pushButton_clear_log = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_log.setEnabled(True)
        self.pushButton_clear_log.setObjectName("pushButton_clear_log")
        self.gridLayout_port.addWidget(self.pushButton_clear_log, 0, 8, 1, 1)
        self.label_ip = QtWidgets.QLabel(self.centralwidget)
        self.label_ip.setObjectName("label_ip")
        self.gridLayout_port.addWidget(self.label_ip, 0, 0, 1, 1)
        self.pushButton_save_log = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_log.setEnabled(True)
        self.pushButton_save_log.setObjectName("pushButton_save_log")
        self.gridLayout_port.addWidget(self.pushButton_save_log, 0, 7, 1, 1)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_baudrate.setMaxVisibleItems(15)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.gridLayout_port.addWidget(self.comboBox_baudrate, 0, 3, 1, 1)
        self.comboBox_port = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_port.sizePolicy().hasHeightForWidth())
        self.comboBox_port.setSizePolicy(sizePolicy)
        self.comboBox_port.setMinimumSize(QtCore.QSize(140, 0))
        self.comboBox_port.setMaximumSize(QtCore.QSize(140, 16777215))
        self.comboBox_port.setCurrentText("")
        self.comboBox_port.setMaxVisibleItems(10)
        self.comboBox_port.setObjectName("comboBox_port")
        self.gridLayout_port.addWidget(self.comboBox_port, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_port.addItem(spacerItem, 0, 6, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_port, 0, 0, 1, 2)
        self.pushButton_bd_get_trace = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bd_get_trace.setObjectName("pushButton_bd_get_trace")
        self.gridLayout.addWidget(self.pushButton_bd_get_trace, 1, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 1, 5, 1)
        self.pushButton_bd_show_trace = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bd_show_trace.setObjectName("pushButton_bd_show_trace")
        self.gridLayout.addWidget(self.pushButton_bd_show_trace, 2, 0, 1, 1)
        self.pushButton_bd_hide_trace = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bd_hide_trace.setObjectName("pushButton_bd_hide_trace")
        self.gridLayout.addWidget(self.pushButton_bd_hide_trace, 3, 0, 1, 1)
        self.pushButton_bd_show_trace_filt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bd_show_trace_filt.setObjectName("pushButton_bd_show_trace_filt")
        self.gridLayout.addWidget(self.pushButton_bd_show_trace_filt, 4, 0, 1, 1)
        self.pushButton_bd_hide_trace_filt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bd_hide_trace_filt.setObjectName("pushButton_bd_hide_trace_filt")
        self.gridLayout.addWidget(self.pushButton_bd_hide_trace_filt, 5, 0, 1, 1)
        self.textBrowser_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_log.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser_log.setStatusTip("")
        self.textBrowser_log.setAutoFillBackground(False)
        self.textBrowser_log.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_log.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_log.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textBrowser_log.setLineWrapColumnOrWidth(0)
        self.textBrowser_log.setReadOnly(True)
        self.textBrowser_log.setAcceptRichText(True)
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.gridLayout.addWidget(self.textBrowser_log, 6, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.comboBox_baudrate.setCurrentIndex(11)
        self.comboBox_port.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_port.setText(_translate("MainWindow", "波特率:"))
        self.pushButton_connect.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_clear_log.setText(_translate("MainWindow", "清空日志"))
        self.label_ip.setText(_translate("MainWindow", "端口:"))
        self.pushButton_save_log.setText(_translate("MainWindow", "保存日志"))
        self.comboBox_baudrate.setItemText(0, _translate("MainWindow", "1200"))
        self.comboBox_baudrate.setItemText(1, _translate("MainWindow", "2400"))
        self.comboBox_baudrate.setItemText(2, _translate("MainWindow", "4800"))
        self.comboBox_baudrate.setItemText(3, _translate("MainWindow", "9600"))
        self.comboBox_baudrate.setItemText(4, _translate("MainWindow", "14400"))
        self.comboBox_baudrate.setItemText(5, _translate("MainWindow", "19200"))
        self.comboBox_baudrate.setItemText(6, _translate("MainWindow", "38400"))
        self.comboBox_baudrate.setItemText(7, _translate("MainWindow", "56000"))
        self.comboBox_baudrate.setItemText(8, _translate("MainWindow", "57600"))
        self.comboBox_baudrate.setItemText(9, _translate("MainWindow", "115200"))
        self.comboBox_baudrate.setItemText(10, _translate("MainWindow", "230400"))
        self.comboBox_baudrate.setItemText(11, _translate("MainWindow", "921600"))
        self.pushButton_bd_get_trace.setText(_translate("MainWindow", "采集北斗轨迹"))
        self.pushButton_bd_show_trace.setText(_translate("MainWindow", "显示原始轨迹"))
        self.pushButton_bd_hide_trace.setText(_translate("MainWindow", "隐藏原始轨迹"))
        self.pushButton_bd_show_trace_filt.setText(_translate("MainWindow", "显示过滤轨迹"))
        self.pushButton_bd_hide_trace_filt.setText(_translate("MainWindow", "隐藏过滤轨迹"))
        self.textBrowser_log.setDocumentTitle(_translate("MainWindow", "运行日志"))

